# MOOSE input file generated by ModelBuilder for project: perm3layer_opt

[Variables]
  [pp]
    initial_condition = 0.0
  []
  [disp_x]
    initial_condition = 0.0
  []
  [disp_y]
    initial_condition = 0.0
  []
  [pp_adjoint]
    solver_sys = 'adjoint'
    initial_condition = 0
  []
  [disp_x_adjoint]
    solver_sys = 'adjoint'
    initial_condition = 0
  []
  [disp_y_adjoint]
    solver_sys = 'adjoint'
    initial_condition = 0
  []
[]

[Mesh]
  [base_mesh]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 200
    ny = 200
    xmin = 0
    xmax = 200.0
    ymin = -50.0
    ymax = 50.0
  []
  [matrix_bottom_bbox]
    type = SubdomainBoundingBoxGenerator
    input = 'base_mesh'
    block_id = 1
    bottom_left = '0.0 -50.0 0'
    top_right = '200.0 -2.0 0'
  []
  [srv_bbox]
    type = SubdomainBoundingBoxGenerator
    input = 'matrix_bottom_bbox'
    block_id = 2
    bottom_left = '0.0 -2.0 0'
    top_right = '200.0 2.0 0'
  []
  [matrix_top_bbox]
    type = SubdomainBoundingBoxGenerator
    input = 'srv_bbox'
    block_id = 3
    bottom_left = '0.0 2.0 0'
    top_right = '200.0 50.0 0'
  []
  [injection_well_nodes]
    type = ExtraNodesetGenerator
    input = 'matrix_top_bbox'
    new_boundary = 'injection_well'
    coord = '20.0 0 0'
  []
  [final_block_rename]
    type = RenameBlockGenerator
    input = 'injection_well_nodes'
    old_block = '1 2 3'
    new_block = 'matrix_bottom srv matrix_top'
  []
  [final_block_rename_1]
    type = RenameBlockGenerator
    input = 'final_block_rename'
    old_block = '1 2 3'
    new_block = 'matrix_bottom srv matrix_top'
  []
[]

[UserObjects]
  [dictator]
    type = PorousFlowDictator
    porous_flow_vars = 'pp'
    number_fluid_phases = 1
    number_fluid_components = 1
  []
[]

[GlobalParams]
  PorousFlowDictator = 'dictator'
[]

[Kernels]
  [dot_pp]
    type = TimeDerivative
    variable = 'pp'
  []
  [flux]
    type = PorousFlowFullySaturatedDarcyBase
    variable = 'pp'
    gravity = '0 0 0'
  []
  [grad_stress_x]
    type = StressDivergenceTensors
    variable = 'disp_x'
    component = 0
    displacements = 'disp_x disp_y'
  []
  [grad_stress_y]
    type = StressDivergenceTensors
    variable = 'disp_y'
    component = 1
    displacements = 'disp_x disp_y'
  []
  [eff_stress_x]
    type = PorousFlowEffectiveStressCoupling
    variable = 'disp_x'
    component = 0
    biot_coefficient = 0.7
    displacements = 'disp_x disp_y'
  []
  [eff_stress_y]
    type = PorousFlowEffectiveStressCoupling
    variable = 'disp_y'
    component = 1
    biot_coefficient = 0.7
    displacements = 'disp_x disp_y'
  []
[]

[Functions]
  [func_kyy]
    type = ParsedFunction
    expression = '1e-20'
  []
  [func_zero]
    type = ParsedFunction
    expression = '0.0'
  []
  [perm_matrix_bottom]
    type = ParsedOptimizationFunction
    expression = '10^alpha'
    param_symbol_names = 'alpha'
    param_vector_name = 'params/perm_1'
  []
  [perm_srv]
    type = ParsedOptimizationFunction
    expression = '10^alpha'
    param_symbol_names = 'alpha'
    param_vector_name = 'params/perm_2'
  []
  [perm_matrix_top]
    type = ParsedOptimizationFunction
    expression = '10^alpha'
    param_symbol_names = 'alpha'
    param_vector_name = 'params/perm_3'
  []
  [injection_pressure_func]
    type = PiecewiseConstant
    x = '0.0 725.0 2023.0 3446.0 4010.0 4486.0 6280.0 7401.0 8565.0 9324.0 10004.0 28800.0'
    y = '12691246.67 12696027.23 12685664.88 12701609.02 12685981.35 12682156.91 12700747.17 12685880.34 12707413.0 12689475.85 12685940.94 14000000.0'
  []
[]

[AuxVariables]
  [perm_yy_var]
    order = 'CONSTANT'
    family = 'MONOMIAL'
  []
  [perm_zz_var]
    order = 'CONSTANT'
    family = 'MONOMIAL'
  []
  [perm_xx_matrix_bottom]
    order = 'CONSTANT'
    family = 'MONOMIAL'
  []
  [perm_xx_srv]
    order = 'CONSTANT'
    family = 'MONOMIAL'
  []
  [perm_xx_matrix_top]
    order = 'CONSTANT'
    family = 'MONOMIAL'
  []
  [stress_xx]
    order = 'CONSTANT'
    family = 'MONOMIAL'
  []
  [stress_xy]
    order = 'CONSTANT'
    family = 'MONOMIAL'
  []
  [stress_yx]
    order = 'CONSTANT'
    family = 'MONOMIAL'
  []
  [stress_yy]
    order = 'CONSTANT'
    family = 'MONOMIAL'
  []
  [strain_xx]
    order = 'CONSTANT'
    family = 'MONOMIAL'
  []
  [strain_xy]
    order = 'CONSTANT'
    family = 'MONOMIAL'
  []
  [strain_yx]
    order = 'CONSTANT'
    family = 'MONOMIAL'
  []
  [strain_yy]
    order = 'CONSTANT'
    family = 'MONOMIAL'
  []
[]

[AuxKernels]
  [perm_yy_aux]
    type = FunctionAux
    variable = 'perm_yy_var'
    function = 'func_kyy'
    execute_on = 'INITIAL TIMESTEP_BEGIN TIMESTEP_END'
  []
  [perm_zz_aux]
    type = FunctionAux
    variable = 'perm_zz_var'
    function = 'func_zero'
    execute_on = 'INITIAL TIMESTEP_BEGIN TIMESTEP_END'
  []
  [perm_xx_matrix_bottom_aux]
    type = FunctionAux
    variable = 'perm_xx_matrix_bottom'
    function = 'perm_matrix_bottom'
    block = 'matrix_bottom'
    execute_on = 'INITIAL TIMESTEP_BEGIN TIMESTEP_END'
  []
  [perm_xx_srv_aux]
    type = FunctionAux
    variable = 'perm_xx_srv'
    function = 'perm_srv'
    block = 'srv'
    execute_on = 'INITIAL TIMESTEP_BEGIN TIMESTEP_END'
  []
  [perm_xx_matrix_top_aux]
    type = FunctionAux
    variable = 'perm_xx_matrix_top'
    function = 'perm_matrix_top'
    block = 'matrix_top'
    execute_on = 'INITIAL TIMESTEP_BEGIN TIMESTEP_END'
  []
  [stress_xx]
    type = RankTwoAux
    rank_two_tensor = 'stress'
    variable = 'stress_xx'
    index_i = 0
    index_j = 0
  []
  [stress_xy]
    type = RankTwoAux
    rank_two_tensor = 'stress'
    variable = 'stress_xy'
    index_i = 0
    index_j = 1
  []
  [stress_yx]
    type = RankTwoAux
    rank_two_tensor = 'stress'
    variable = 'stress_yx'
    index_i = 1
    index_j = 0
  []
  [stress_yy]
    type = RankTwoAux
    rank_two_tensor = 'stress'
    variable = 'stress_yy'
    index_i = 1
    index_j = 1
  []
  [strain_xx]
    type = RankTwoAux
    rank_two_tensor = 'total_strain'
    variable = 'strain_xx'
    index_i = 0
    index_j = 0
  []
  [strain_xy]
    type = RankTwoAux
    rank_two_tensor = 'total_strain'
    variable = 'strain_xy'
    index_i = 0
    index_j = 1
  []
  [strain_yx]
    type = RankTwoAux
    rank_two_tensor = 'total_strain'
    variable = 'strain_yx'
    index_i = 1
    index_j = 0
  []
  [strain_yy]
    type = RankTwoAux
    rank_two_tensor = 'total_strain'
    variable = 'strain_yy'
    index_i = 1
    index_j = 1
  []
[]

[VectorPostprocessors]
  [grad_perm_matrix_bottom]
    type = ElementOptimizationDiffusionCoefFunctionInnerProduct
    variable = 'pp_adjoint'
    forward_variable = 'pp'
    function = 'perm_matrix_bottom'
    block = 'matrix_bottom'
    execute_on = 'ADJOINT_TIMESTEP_END'
    outputs = 'none'
  []
  [grad_perm_srv]
    type = ElementOptimizationDiffusionCoefFunctionInnerProduct
    variable = 'pp_adjoint'
    forward_variable = 'pp'
    function = 'perm_srv'
    block = 'srv'
    execute_on = 'ADJOINT_TIMESTEP_END'
    outputs = 'none'
  []
  [grad_perm_matrix_top]
    type = ElementOptimizationDiffusionCoefFunctionInnerProduct
    variable = 'pp_adjoint'
    forward_variable = 'pp'
    function = 'perm_matrix_top'
    block = 'matrix_top'
    execute_on = 'ADJOINT_TIMESTEP_END'
    outputs = 'none'
  []
[]

[FluidProperties]
  [oil]
    type = SimpleFluidProperties
    bulk_modulus = 1200000000.0
    viscosity = 0.0012
    density0 = 825.0
    thermal_expansion = 0.0008
    cp = 2100.0
    cv = 2000.0
    porepressure_coefficient = 1.0
  []
[]

[Materials]
  [porosity_matrix_bottom]
    type = PorousFlowPorosityConst
    porosity = 0.01
    block = 'matrix_bottom'
  []
  [permeability_matrix_bottom]
    type = PorousFlowPermeabilityConstFromVar
    perm_xx = 'perm_xx_matrix_bottom'
    perm_yy = 'perm_yy_var'
    perm_zz = 'perm_zz_var'
    block = 'matrix_bottom'
  []
  [elasticity_tensor_matrix_bottom]
    type = ComputeIsotropicElasticityTensor
    youngs_modulus = 50000000000.0
    poissons_ratio = 0.2
    block = 'matrix_bottom'
  []
  [porosity_srv]
    type = PorousFlowPorosityConst
    porosity = 0.14
    block = 'srv'
  []
  [permeability_srv]
    type = PorousFlowPermeabilityConstFromVar
    perm_xx = 'perm_xx_srv'
    perm_yy = 'perm_yy_var'
    perm_zz = 'perm_zz_var'
    block = 'srv'
  []
  [elasticity_tensor_srv]
    type = ComputeIsotropicElasticityTensor
    youngs_modulus = 50000000000.0
    poissons_ratio = 0.2
    block = 'srv'
  []
  [porosity_matrix_top]
    type = PorousFlowPorosityConst
    porosity = 0.01
    block = 'matrix_top'
  []
  [permeability_matrix_top]
    type = PorousFlowPermeabilityConstFromVar
    perm_xx = 'perm_xx_matrix_top'
    perm_yy = 'perm_yy_var'
    perm_zz = 'perm_zz_var'
    block = 'matrix_top'
  []
  [elasticity_tensor_matrix_top]
    type = ComputeIsotropicElasticityTensor
    youngs_modulus = 50000000000.0
    poissons_ratio = 0.2
    block = 'matrix_top'
  []
  [temperature]
    type = PorousFlowTemperature
  []
  [biot_modulus]
    type = PorousFlowConstantBiotModulus
    biot_coefficient = 0.7
    solid_bulk_compliance = 2e-11
    fluid_bulk_modulus = 1200000000.0
    block = 'matrix_bottom srv matrix_top'
  []
  [massfrac]
    type = PorousFlowMassFraction
  []
  [simple_fluid]
    type = PorousFlowSingleComponentFluid
    fp = 'oil'
    phase = 0
  []
  [PS]
    type = PorousFlow1PhaseFullySaturated
    porepressure = 'pp'
  []
  [relp]
    type = PorousFlowRelativePermeabilityConst
    phase = 0
  []
  [eff_fluid_pressure_qp]
    type = PorousFlowEffectiveFluidPressure
  []
  [strain]
    type = ComputeSmallStrain
    displacements = 'disp_x disp_y'
    block = 'matrix_bottom srv matrix_top'
  []
  [stress]
    type = ComputeLinearElasticStress
    block = 'matrix_bottom srv matrix_top'
  []
  [vol_strain]
    type = PorousFlowVolumetricStrain
    displacements = 'disp_x disp_y'
  []
[]

[BCs]
  [injection_pressure]
    type = FunctionDirichletBC
    variable = 'pp'
    boundary = 'injection_well'
    function = 'injection_pressure_func'
  []
  [confinex]
    type = DirichletBC
    variable = 'disp_x'
    boundary = 'left right'
    value = 0
  []
  [confiney]
    type = DirichletBC
    variable = 'disp_y'
    boundary = 'top bottom'
    value = 0
  []
[]

[Problem]
  nl_sys_names = 'nl0 adjoint'
  kernel_coverage_check = false
[]

[Reporters]
  [data]
    type = OptimizationData
    objective_name = 'objective_value'
    variable = 'disp_y'
    outputs = 'none'
  []
  [params]
    type = ConstantReporter
    real_vector_names = 'perm_1 perm_2 perm_3'
    real_vector_values = '1E-15; 1E-15; 1E-15'
    outputs = 'none'
  []
[]

[DiracKernels]
  [misfit]
    type = ReporterTimePointSource
    variable = 'disp_y_adjoint'
    value_name = 'data/misfit_values'
    x_coord_name = 'data/measurement_xcoord'
    y_coord_name = 'data/measurement_ycoord'
    z_coord_name = 'data/measurement_zcoord'
    time_name = 'data/measurement_time'
  []
[]

[Executioner]
  type = 'TransientAndAdjoint'
  forward_system = 'nl0'
  adjoint_system = 'adjoint'
  end_time = 28800
  verbose = true
  l_tol = 0.001
  l_max_its = 2000
  nl_max_its = 200
  nl_abs_tol = 0.001
  nl_rel_tol = 0.001
  [TimeStepper]
    type = ConstantDT
    dt = 600
  []
[]

[Outputs]
  console = true
  [exodus]
    type = Exodus
  []
  [csv]
    type = CSV
  []
[]