# Generated by Shenyao brain. :)

[Optimization]
[]

[Mesh]
    type = GeneratedMesh
    dim = 2
    nx = 10
    ny = 10
    xmax = 100
    ymax = 200
[]

[OptimizationReporter]
    type = GeneralOptimization
    objective_name = objective_value
    parameter_names = 'permeability'
    num_values = '3'
    initial_condition = '5e-21 3e-18 1e-23'
    lower_bound = '1e-23 1e-23 1e-23'
    upper_bound = '1e-17 1e-17 1e-17'
[]

[Reporters]
    [main]
        type = OptimizationData
        measurement_points =
    []